global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'notification-system'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    metrics_path: '/api/v1/metrics'
    static_configs:
      - targets: ['api-gateway:8020']
        labels:
          service: 'api-gateway'
          environment: 'local'

  - job_name: 'user-service'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['user-service:3001']
        labels:
          service: 'user-service'
          environment: 'local'

  - job_name: 'email-service'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['email-service:8001']
        labels:
          service: 'email-service'
          environment: 'local'

  - job_name: 'push-service'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['push-service:8000']
        labels:
          service: 'push-service'
          environment: 'local'

  - job_name: 'template-service'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['template-service:8003']
        labels:
          service: 'template-service'
          environment: 'local'

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
        labels:
          service: 'rabbitmq'
